### ISSUE TITLE
take a look at how I fixed quadratic complexity of left associated chain without CatList

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-free#68]
Hey folks, 

I also had the issue of quadratic complexity on left associated chains on Free monad, and I fixed it by changing type of Free(Seq) this way:
		  
```diff
data Seq f a where
    Pure :: a -> Seq f a
+  Lift :: f a -> Seq f a
-  Roll ::     f a -> (a -> Seq f b) -> Seq f b
+  Roll :: Seq f a -> (a -> Seq f b) -> Seq f b
```

And by placing `Seq f a` in `Roll`  node instead of `f a`, I've avoided using CatList and chain is pretty simple as well:
```js
Seq.prototype.chain = (f) => {
  // this way in Roll we don't have any `Pure` node
  if (Pure.is(this)) {
    return f(this.a)
  }
  return Roll(this, f)
} 
```

so when one associates chain to left `Roll` nodes are created/nested, and then on `fold` it could be inspected and interpreted safely.

I don't know Purescript that well, and can't suggest any way to implement Free this way, with lack of GADTs. but in case someone knows how it's possible, maybe implementation could become a bit simpler and straightforward.

this is the [issue](https://github.com/safareli/free/issues/36) and fix [commit](https://github.com/safareli/free/issues/36)

**Comment by paf31** [comment]
Can you demonstrate the problem with left associated binds?

I think we would need to see an implementation and to compare performance. Full GADTs shouldn't be necessary, just `Exists`.

**Comment by garyb** [comment]
I think this is meant as an alternative to `CatList`, as if you look at the benchmarks for our current implementation we already don't have quadratic left bind.

**Comment by jdegoes** [comment]
I agree this representation would be faster / more direct. It's already used in Scala and does not require GADTs (as @paf31 notes, exists is sufficient or you can just directly skolemize the existential).

**Comment by safareli** [comment]
I know that ps-free has no issue with left associated binds. My previous js implementation had this issue and I've fixed it with the diff I've linked.

Reason I've opened this issue is that, I think my variation is simpler, than catlist version and possibly a bit faster.

`Exists` looks interesting. if i understand it correctly defining Free using Exists would looks like this?
```
data Free f a
  = Pure a
  | Lift (f a)
  | Roll (FreeRoll f a)
data FreeRoll f a= Exists (RollF f a)
data RollF f b a = RollF (Free f b) (b -> Free f a)
```

**Comment by safareli** [comment]
@garyb @paf31 do you wan't to see PR addressing this issue?

**Comment by natefaubion** [comment]
FWIW, this representation does not solve efficiency with regards to reflection. To recap, the naive version:

```purescript
data Free f a
  = Pure a
  | Roll (f (Free f a))
```

Reflection (peeking at the head, or `resume`) with this representation is very cheap. It's just like `uncons` on a `List`. But just like `snoc` on a list, left-associative binds with this representation are very expensive to construct. Now your version:

```purescript
data Free f a
  = Pure a
  | forall b. Bind (f b) (b -> Free f a)
```

This is the exact _opposite_ tradeoff. It's very cheap to construct, but whenever you want to peek at the head, you have to fully walk the left-side of `Bind`, and re-associate all the intermediate binds as you go. Once the binds are re-associated, you're good though. I think this should be equivalent to "Free Monads for Less".

The point of the current representation is to get the best of both worlds (somewhat). Construction is _somewhat_ cheap (and chiefly, not quadratic), and peeking at the head is cheap. Binds don't need to be reassociated because they are just suspended in an efficient :crossed_fingers:  data structure.

Whether this is cheaper in practice or not depends on how you use it. If you only interpret some `Free` once, indiscriminately, then the suggested alternative is probably faster. If you _know_ everything is right-associated, the _naive_ version is faster. There's also likely room to improve the underlying data structure in the current version.

**Comment by natefaubion** [comment]
On looking at your version again, I noticed you rather have:

```purescript
data Free f a
  = Pure a
  | forall b. Bind (Free f b) (b -> Free f a)
```

So to write `resume`, you still have to walk the left-side of `Bind` and re-associate, it's just not via `map`. You still have to re-associate by building a new chain of `Bind`s.

**Comment by safareli** [comment]
ah now i see what's the point of `resume`. so it either gives lifted `f a` if that's node in free  or ... (don't understand this other case, can you explain it a bit more?). 

So with my implementation if you write resume you would need to dig in left branch, to get first node so that might be O(n) in worst case.

**Comment by natefaubion** [comment]
`resume` is the eliminator for `Free`. It reflects whatever representation into the naive version.

```purescript
data Free
  = Pure a
  | Roll (f (Free f a))

newtype Free f a = Free (Either (f (Free f a)) a)

resume
  :: forall f a
   . Functor f
  => Free f a
  -> Either (f (Free f a)) a
```

These representation are the same. So the naive version does not _need_ `resume` because you can just pattern match on it directly in O(1) time (at the cost of terrible left-associative bind performance).

For the suggested alternative, you'd maybe do something like this (I haven't compiled this, so I have no idea if this is actually right 😆):

```purescript
data Free f a
  = Pure a
  | Lift (f a)
  | forall b. Bind (Free f b) (b → Free f a)

resume
  :: forall f a
   . Functor f
  => Free f a
  -> Either (f (Free f a)) a
resume = case _ of
  Pure a -> Right a
  Lift f -> Left (Pure <$> f)
  Bind f k -> reassoc k f
  where
  reassoc k = case _ of
    Pure a -> resume (k a)
    Lift f -> Left (k <$> f)
    Bind f k' -> reassoc (\a → k' a >>= k) f
```

So to observe the head of a `Free` you are paying to walk the left side of bind until you reach a `Lift` case, re-associating all the binds as you go (making it right-associative). So this eliminates the problems of quadratic left-associative binds by making reflection potentially O(n).

The point of reflection-without-remorse is that it's supposed to do both. Observing the head should be O(1), and left-associative binds should not be quadratic. According to `Data.CatList`, it should be O(1) amortized, with any given `uncons` potentially being O(n). How this all works out in practice compared to your suggested alternative, I'm not sure. Reflection-without-remorse has more "machinery" (and we are in a strict language), so it may actually be slower in practice.

**Comment by safareli** [comment]
Thanks! makes sense now

**Comment by safareli** [comment]
> I agree this representation would be faster / more direct. It's already used in Scala and does not require GADTs (as @paf31 notes, exists is sufficient or you can just directly skolemize the existential).

@jdegoes which lib is using that representation? as looks like current ps version is better.

**Comment by jdegoes** [comment]
@safareli Scalaz, for example. It's true it does not solve the problem with reflection.

**Comment by JordanMartinez** [comment]
Looks like this issue can be closed.
